### PR TITLE
parallax page

### PR DESCRIPTION
**Pull request by frypan01**
## Check List (Check all the applicable boxes) 

- [x ] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Screenshot (97)
Screenshot (98)

### CODE REVIEW

**Comment by biratdatta** [comment]
The files are conflicting, please look into it

**Comment by biratdatta** [comment]
Change the name of the files and upload

**Comment by frypan01** [comment]
I am Unable to resolve this one !! How should I do this?

**Comment by biratdatta** [comment]
Change the files name from style.css to something else

**Comment by frypan01** [comment]
please wait...

**Pull request closed without merging**
