### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by nayanmapara**
Issue Resolved: #71 

Add "**hacktoberfest**" tag if you find this pull request worthy of it.

### CODE REVIEW

**Comment by biratdatta** [comment]
Can you update the readme frequently @nayanmapara

**Comment by nayanmapara** [comment]
> Can you update the readme frequently @nayanmapara

I cannot promise you, but you can tag me when you need it updated and I will try to do it.

**Comment by biratdatta** [comment]
Cool

**Comment by JayrajSingh65** [comment]
> Cool

- hey i updated readme file check out my pr

**Pull request merged**
