### PR TITLE
Sourodip20kar.md

### PR DESCRIPTION
**Pull request by Sirsha2468**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Sirsha2468** [comment]
Can you please merge my request or can you tell me if I need to do any type of modification?

**Comment by biratdatta** [comment]
Please try with better topics

**Comment by Sirsha2468** [comment]
> Please try with better topics 

Okay thank you 💓

**Comment by Sirsha2468** [comment]
> Please try with better topics

I have uploaded one new file, i.e. CSS animation project, kindly accept that PR. Thank you so much.

**Pull request closed without merging**
